---
- name: Preflight
  hosts: localhost:automationcontroller:automationedacontroller:automationeda:automationgateway:automationhub
  gather_facts: false
  any_errors_fatal: true
  max_fail_percentage: 0
  tasks:
    - name: Set Common Groups
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.common
        tasks_from: set_groups.yml

- name: Validate and extract artifact
  hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true
  max_fail_percentage: 0
  tasks:
    - name: Extract and validate artifact
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.artifact
        tasks_from: extract.yml

- name: Stop AAP services
  ansible.builtin.import_playbook: ../common/stop_services.yaml

- name: Import databases and update secrets
  hosts: controller_groups:eda_groups:gateway_groups:hub_groups
  gather_facts: false
  any_errors_fatal: true
  max_fail_percentage: 0
  vars:
    aap_platform: "containerized"
  tasks:
    - name: Import controller
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationcontroller
        tasks_from: import.yml
      when:
        - groups.get('controller_groups', []) | length > 0
        - inventory_hostname == groups['controller_groups'][0]

    - name: Import hub
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationhub
        tasks_from: import.yml
      when:
        - groups.get('hub_groups', []) | length > 0
        - inventory_hostname == groups['hub_groups'][0]

    - name: Import gateway
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationgateway
        tasks_from: import.yml
      when:
        - groups.get('gateway_groups', []) | length > 0
        - inventory_hostname == groups['gateway_groups'][0]

    - name: Import EDA
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationeda
        tasks_from: import.yml
      when:
        - groups.get('eda_groups', []) | length > 0
        - inventory_hostname == groups['eda_groups'][0]

- name: Start AAP services
  ansible.builtin.import_playbook: ../containerized/start_aap.yaml


- name: Reconcile
  hosts: controller_groups:eda_groups:gateway_groups:hub_groups
  gather_facts: false
  any_errors_fatal: true
  max_fail_percentage: 0
  vars:
    aap_platform: 'containerized'
  tasks:
    - name: Reconcile gateway
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationgateway
        tasks_from: reconcile.yml
      when:
        - groups.get('gateway_groups', []) | length > 0
        - inventory_hostname == groups['gateway_groups'][0]

    - name: Reconcile controller
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationcontroller
        tasks_from: reconcile.yml
      when:
        - groups.get('controller_groups', []) | length > 0
        - inventory_hostname == groups['controller_groups'][0]

    - name: Reconcile hub
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationhub
        tasks_from: reconcile.yml
      when:
        - groups.get('hub_groups', []) | length > 0
        - inventory_hostname == groups['hub_groups'][0]

    - name: Reconcile EDA
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationeda
        tasks_from: reconcile.yml
      when:
        - groups.get('eda_groups', []) | length > 0
        - inventory_hostname == groups['eda_groups'][0]
