---
- name: Load AAP secrets from YAML file
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Include AAP secrets
      ansible.builtin.include_vars:
        file: '{{ archive_dir.rstrip("/") }}/secrets.yml'
        name: aap_secrets

- name: Update podman secret for Automation Controller
  hosts: automationcontroller
  gather_facts: false
  tasks:
    - name: Update controller secret
      containers.podman.podman_secret:
        state: present
        name: controller_secret_key
        data: "{{ hostvars['localhost']['aap_secrets']['controller_secret'] }}"
        skip_existing: '{{ _podman_idempotence | ternary(omit, true) }}'
        force: '{{ _podman_idempotence | ternary(omit, true) }}'

- name: Update podman secret for Automation Hub
  hosts: automationhub
  gather_facts: false
  tasks:
    - name: Update hub secret
      containers.podman.podman_secret:
        state: present
        name: hub_secret_key
        data: "{{ hostvars['localhost']['aap_secrets']['hub_secret'] }}"
        skip_existing: '{{ _podman_idempotence | ternary(omit, true) }}'
        force: '{{ _podman_idempotence | ternary(omit, true) }}'

- name: Update podman secret for Automation EDA
  hosts: automationeda
  gather_facts: false
  tasks:
    - name: Update EDA secret
      containers.podman.podman_secret:
        state: present
        name: eda_secret_key
        data: "{{ hostvars['localhost']['aap_secrets']['eda_secret'] }}"
        skip_existing: '{{ _podman_idempotence | ternary(omit, true) }}'
        force: '{{ _podman_idempotence | ternary(omit, true) }}'

- name: Update podman secret for Automation Gateway
  hosts: automationgateway
  gather_facts: false
  tasks:
    - name: Update gateway secret
      containers.podman.podman_secret:
        state: present
        name: gateway_secret_key
        data: "{{ hostvars['localhost']['aap_secrets']['gateway_secret'] }}"
        skip_existing: '{{ _podman_idempotence | ternary(omit, true) }}'
        force: '{{ _podman_idempotence | ternary(omit, true) }}'

...
