---
- name: Start Monitoring Services
  hosts: automationcontroller:automationhub:automationeda:automationgateway
  gather_facts: false
  tasks:
    - name: Start monitoring
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.pcp
        tasks_from: start_service.yml

- name: Start EDA Services
  hosts: automationeda
  gather_facts: false
  tasks:
    - name: Start EDA
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationeda
        tasks_from: start_service.yml

- name: Start Hub Services
  hosts: automationhub
  gather_facts: false
  tasks:
    - name: Start Hub
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationhub
        tasks_from: start_service.yml

- name: Start Controller Services
  hosts: automationcontroller
  gather_facts: false
  tasks:
    - name: Start Controller
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationcontroller
        tasks_from: start_service.yml

- name: Start Execution Nodes Services
  hosts: execution_nodes
  gather_facts: false
  tasks:
    - name: Start Execution Nodes services
      ansible.builtin.systemd:
        name: receptor
        state: started
        scope: user

- name: Start Gateway Services
  hosts: automationgateway
  gather_facts: false
  tasks:
    - name: Start Gateway
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationgateway
        tasks_from: start_service.yml
