---
- name: Initialize artifact
  hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true
  max_fail_percentage: 0
  become: false
  tasks:
    - name: Initialize artifact locally
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.artifact
        tasks_from: init.yml

- name: Export into artifact
  hosts: automationcontroller:automationedacontroller:automationgateway:automationhub
  gather_facts: false
  any_errors_fatal: true
  max_fail_percentage: 0
  become: true
  tasks:
    - name: Export components into artifact
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.artifact
        tasks_from: build.yml

- name: Package artifact
  hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true
  max_fail_percentage: 0
  become: false
  vars:
    aap_platform: "rpm"
  tasks:
    - name: Package artifact locally
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.artifact
        tasks_from: package.yml
