---
- name: Export database
  hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true
  become: false
  vars:
    export_dest: "{{ lookup('env', 'PWD') }}/db_export"
    _export_dest: "{{ export_dest.rstrip('/') }}"
  tasks:
    - name: Ensure ./db_export folder exists
      ansible.builtin.file:
        path: "{{ _export_dest }}/{{ item }}"
        state: directory
        mode: "0750"
      loop:
        - 'controller'
        - 'eda'
        - 'gateway'
        - 'hub'

- name: Backup Automation Controller
  hosts: automationcontroller[0]:automationhub[0]:automationedacontroller[0]:automationgateway[0]
  gather_facts: false
  become: false
  vars:
    export_dir: "/tmp/backups/automation-platform"
    _export_dir: "{{ export_dir.rstrip('/') }}"
    export_dest: "{{ lookup('env', 'PWD') }}/db_export"
    _export_dest: "{{ export_dest.rstrip('/') }}"
  tasks:
    - name: Automation controller DB export
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationcontroller
        tasks_from: db_export.yml
      vars:
        postgresql_export_dir: "{{ _export_dir }}"
        postgresql_export_dest: "{{ _export_dest }}"
      when:
        - groups.get('automationcontroller', []) | length > 0
        - inventory_hostname in groups.get('automationcontroller', [])

    - name: Automation hub DB export
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationhub
        tasks_from: db_export.yml
      vars:
        postgresql_export_dir: "{{ _export_dir }}"
        postgresql_export_dest: "{{ _export_dest }}"
      when:
        - groups.get('automationhub', []) | length > 0
        - inventory_hostname in groups.get('automationhub', [])

    - name: Automation EDA DB export
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationeda
        tasks_from: db_export.yml
      vars:
        postgresql_export_dir: "{{ _export_dir }}"
        postgresql_export_dest: "{{ _export_dest }}"
      when:
        - groups.get('automationedacontroller', []) | length > 0
        - inventory_hostname in groups.get('automationedacontroller', [])

    - name: Automation gateway DB export
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationgateway
        tasks_from: db_export.yml
      vars:
        postgresql_export_dir: "{{ _export_dir }}"
        postgresql_export_dest: "{{ _export_dest }}"
      when:
        - groups.get('automationgateway', []) | length > 0
        - inventory_hostname in groups.get('automationgateway', [])

- name: Download DB checksum files
  hosts: localhost
  gather_facts: false
  become: false
  vars:
    export_dest: "{{ lookup('env', 'PWD') }}/db_export"
    _export_dest: "{{ export_dest.rstrip('/') }}"
  tasks:
    - name: "Create file for database checksums"
      ansible.builtin.copy:
        content: "{{ groups['all'] | map('extract', hostvars) | selectattr('db_file_checksum', 'defined') | map(attribute='db_file_checksum') | join('\n') }}\n"
        dest: "{{ _export_dest }}/files.{{ postgresql_checksum_algo | default('sha256') }}"
        mode: "0640"

...
