---
- name: Initialize facts
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Initialize empty secrets dictionary
      ansible.builtin.set_fact:
        aap_secrets: {}

- name: Gather Secret Key from Automation Controller
  hosts: automationcontroller
  gather_facts: false
  become: true
  run_once: true
  tasks:
    - name: Automation controller secret export
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationcontroller
        tasks_from: get_secret.yml

- name: Gather Secret Key from Automation Hub
  hosts: automationhub
  gather_facts: false
  become: true
  run_once: true
  tasks:
    - name: Automation hub secret export
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationhub
        tasks_from: get_secret.yml

- name: Gather Secret Key from EDA Controller
  hosts: automationedacontroller
  gather_facts: false
  become: true
  run_once: true
  tasks:
    - name: Automation EDA secret export
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationeda
        tasks_from: get_secret.yml

- name: Gather Secret Key from Automation Gateway
  hosts: automationgateway
  gather_facts: false
  become: true
  run_once: true
  tasks:
    - name: Automation gateway secret export
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationgateway
        tasks_from: get_secret.yml

- name: Export consolidated secrets to YAML
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Write secrets to YAML file
      ansible.builtin.copy:
        content: "{{ aap_secrets | to_nice_yaml }}"
        dest: '{{ lookup("env", "PWD") }}/secrets.yml'
        mode: "0600"

...
