---
- name: Stop Monitoring Services
  hosts: automationcontroller:automationhub:automationedacontroller:automationgateway
  gather_facts: false
  tasks:
    - name: Stop monitoring service
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
      become: true
      loop:
        - pmproxy
        - pmcd

- name: Stop EDA Services
  hosts: automationedacontroller
  gather_facts: false
  tasks:
    - name: Stop all EDA services
      ansible.builtin.command:
        cmd: "{{ item }}"
      register: command_output
      changed_when: command_output.rc != 0
      become: true
      loop:
        - automation-eda-controller-service stop
        - automation-eda-controller-event-stream-service stop

- name: Stop Hub Services
  hosts: automationhub
  gather_facts: false
  tasks:
    - name: Stop all Hub services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
      become: true
      loop:
        - pulpcore-api
        - pulpcore-content

- name: Stop Controller Services
  hosts: automationcontroller
  gather_facts: false
  tasks:
    - name: Stop Automation Controller services
      ansible.builtin.command: automation-controller-service stop
      register: command_output
      changed_when: command_output.rc != 0
      become: true

- name: Stop Gateway Services
  hosts: automationgateway
  gather_facts: false
  tasks:
    - name: Stop Gateway services
      ansible.builtin.command: automation-gateway-service stop
      register: command_output
      changed_when: command_output.rc != 0
      become: true
