---
__preflight_no_log: "{{ not (disable_no_log | default(false) | bool) }}"

preflight_ocp_namespace: "{{ ocp_namespace | default('aap') }}"
preflight_aap_instance_name: "{{ aap_instance_name | default('aap') }}"
preflight_aap_cr_kind: "AnsibleAutomationPlatform"
preflight_operator_namespace: "{{ preflight_ocp_namespace }}"
preflight_aap_cr_api_version: "aap.ansible.com/v1alpha1"
preflight_controller_manage_cmd: "awx-manage"
preflight_gateway_manage_cmd: "aap-gateway-manage"

preflight_temp_pvc_size: "{{ temp_pvc_size | default('60Gi') }}"

preflight_known_rwx_storage_classes:
  - nfs-local-rwx
  - ocs-storagecluster-cephfs
  - odf-cephfs
  - managed-nfs-storage
  - nfs
...
