---
- name: Get eda secrets
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.operations
    tasks_from: get_secret.yml
  vars:
    component_name: "{{ automationeda_component_name }}"
...
