---
- name: Get DB credentials for controller
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.operations
    tasks_from: get_db_credentials.yml
  vars:
    component_name: "{{ automationcontroller_component_name }}"

- name: Restore database for controller
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.operations
    tasks_from: db_import.yml
  vars:
    component_name: "{{ automationcontroller_component_name }}"

- name: Update secrets for controller
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.operations
    tasks_from: update_secret.yml
  vars:
    component_name: "{{ automationcontroller_component_name }}"
