---
automationgateway_component_name: gateway

_automationgateway_cleanup_ocp_script: >-
  from aap_gateway_api.models import HTTPPort, ServiceNode, Route;
  HTTPPort.objects.all().delete();
  Route.objects.all().delete();
  ServiceNode.objects.all().delete()

_automationgateway_cleanup_containerized_script: >-
  from aap_gateway_api.models import HTTPPort, ServiceNode;
  HTTPPort.objects.all().delete();
  ServiceNode.objects.all().delete()
...
