---
- name: Preflight gateway
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.operations
    tasks_from: preflight.yml
  vars:
    component_name: "{{ automationgateway_component_name }}"
...
