---
- name: Start gateway services
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.operations
    tasks_from: start_service.yml
  vars:
    component_name: "{{ automationgateway_component_name }}"
...
