---
- name: Initialize artifact
  hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true
  max_fail_percentage: 0
  vars:
    aap_platform: "operator"
  tasks:
    - name: Initialize artifact locally
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.artifact
        tasks_from: init.yml

- name: Export from OCP
  hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true
  max_fail_percentage: 0
  vars:
    aap_platform: "operator"
  tasks:
    - name: Export gateway (includes AAP version discovery)
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationgateway
        tasks_from: export.yml

    - name: Export controller
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationcontroller
        tasks_from: export.yml

    - name: Export hub
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationhub
        tasks_from: export.yml

    - name: Export EDA
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationeda
        tasks_from: export.yml

- name: Package artifact
  hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true
  max_fail_percentage: 0
  vars:
    aap_platform: "operator"
  tasks:
    - name: Package artifact locally
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.artifact
        tasks_from: package.yml

- name: Validate artifact
  ansible.builtin.import_playbook: ../common/validate_artifact.yaml
