---
- name: Export hub database
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.operations
    tasks_from: db_export.yml
  vars:
    component_name: "{{ automationhub_component_name }}"
...
