---
- name: Get DB credentials for hub
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.operations
    tasks_from: get_db_credentials.yml
  vars:
    component_name: "{{ automationhub_component_name }}"

- name: Restore database for hub
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.operations
    tasks_from: db_import.yml
  vars:
    component_name: "{{ automationhub_component_name }}"

- name: Update secrets for hub
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.operations
    tasks_from: update_secret.yml
  vars:
    component_name: "{{ automationhub_component_name }}"
