---
- name: Start hub services
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.operations
    tasks_from: start_service.yml
  vars:
    component_name: "{{ automationhub_component_name }}"
