---
- name: Validate artifact
  hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  max_fail_percentage: 0
  tasks:
    - name: Temporarily unpack artifact
      ansible.builtin.unarchive:
        src: "{{ __artifact_dest_dir }}/{{ __artifact_filename }}"
        dest: "{{ __artifact_dest_dir }}"

    - name: Run artifact validation
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.validate_artifact
      vars:
        validate_artifact_dir: "{{ __artifact_dest_dir }}/{{ __artifact_build_dir | basename }}"

    - name: Clean up extracted artifact
      ansible.builtin.file:
        path: "{{ __artifact_dest_dir }}/{{ __artifact_build_dir | basename }}"
        state: absent
