---
__operations_no_log: "{{ (disable__no_log | default(false) | bool) | ternary(false, true) }}"

__operations_artifact_extract_dir: "{{ artifact_dir }}/artifact"

operations_ocp_namespace: "{{ ocp_namespace | default('aap') }}"
operations_aap_instance_name: "{{ aap_instance_name | default('aap') }}"

operations_gateway_admin_user: "admin"
operations_validate_certs: false
