---
- name: Delete controller migration jobs
  kubernetes.core.k8s:
    api_version: batch/v1
    kind: Job
    namespace: "{{ ocp_utils_ocp_namespace }}"
    label_selectors:
      - "app.kubernetes.io/component=automationcontroller"
    state: absent
    wait: true
    wait_timeout: 300
