---
- name: Read PostgreSQL configuration secret
  kubernetes.core.k8s_info:
    kind: Secret
    name: "{{ ocp_pg_config_secret }}"
    namespace: "{{ ocp_utils_ocp_namespace }}"
  failed_when: _ocp_utils_pg_config_secret.resources | length == 0
  no_log: "{{ __ocp_utils_no_log }}"
  register: _ocp_utils_pg_config_secret

- name: Set database credential facts
  ansible.builtin.set_fact:
    _ocp_utils_db_host: "{{ _ocp_utils_pg_config_secret.resources[0].data.host | b64decode }}"
    _ocp_utils_db_port: "{{ _ocp_utils_pg_config_secret.resources[0].data.port | b64decode }}"
    _ocp_utils_db_name: "{{ _ocp_utils_pg_config_secret.resources[0].data.database | b64decode }}"
    _ocp_utils_db_user: "{{ _ocp_utils_pg_config_secret.resources[0].data.username | b64decode }}"
    _ocp_utils_db_password: "{{ _ocp_utils_pg_config_secret.resources[0].data.password | b64decode }}"
  no_log: "{{ __ocp_utils_no_log }}"

- name: Read gateway postgres secret for admin password
  kubernetes.core.k8s_info:
    kind: Secret
    name: "{{ __ocp_utils_component_postgres_secrets['gateway'] }}"
    namespace: "{{ ocp_utils_ocp_namespace }}"
  failed_when: _ocp_utils_gw_pg_secret.resources | length == 0
  no_log: "{{ __ocp_utils_no_log }}"
  register: _ocp_utils_gw_pg_secret
  when: _ocp_utils_pg_config_secret.resources[0].data.postgres_admin_password is not defined

- name: Set admin password from component secret
  ansible.builtin.set_fact:
    _ocp_utils_db_admin_password: "{{ _ocp_utils_pg_config_secret.resources[0].data.postgres_admin_password | b64decode }}"
  no_log: "{{ __ocp_utils_no_log }}"
  when: _ocp_utils_pg_config_secret.resources[0].data.postgres_admin_password is defined

- name: Set admin password from gateway secret
  ansible.builtin.set_fact:
    _ocp_utils_db_admin_password: "{{ _ocp_utils_gw_pg_secret.resources[0].data.postgres_admin_password | b64decode }}"
  no_log: "{{ __ocp_utils_no_log }}"
  when: _ocp_utils_pg_config_secret.resources[0].data.postgres_admin_password is not defined
...
