---
- name: "Run manage command (OCP)"
  kubernetes.core.k8s_exec:
    namespace: "{{ ocp_utils_ocp_namespace }}"
    pod: "{{ _manage_pod_name }}"
    container: "{{ _manage_container_name | default(omit) }}"
    command: "{{ _manage_command }}"
  failed_when: _ocp_utils_manage_result_ocp.rc | default(1) != 0
  register: _ocp_utils_manage_result_ocp
  when: aap_platform == 'operator'

- name: "Run manage command (containerized)"
  containers.podman.podman_container_exec:
    name: "{{ _manage_container_name }}"
    command: "{{ _manage_command }}"
  failed_when: _ocp_utils_manage_result_ctr.rc != 0
  register: _ocp_utils_manage_result_ctr
  when: aap_platform == 'containerized'

- name: Set manage command result
  ansible.builtin.set_fact:
    _ocp_utils_manage_result: "{{ _ocp_utils_manage_result_ocp if aap_platform == 'operator' else _ocp_utils_manage_result_ctr }}"
...
