---
- name: Extract artifact archive
  ansible.builtin.unarchive:
    src: "{{ artifact_dir }}/{{ artifact_filename }}"
    dest: "{{ artifact_dir }}"

- name: Validate extracted artifact
  ansible.builtin.include_tasks: validate.yml

- name: Load artifact secrets
  ansible.builtin.include_vars:
    file: "{{ artifact_dir }}/artifact/secrets.yml"
    name: artifact_secrets

- name: Load artifact manifest
  ansible.builtin.include_vars:
    file: "{{ artifact_dir }}/artifact/manifest.yml"
    name: artifact_manifest
...
