---
- name: Reconcile gateway
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.automationgateway
    tasks_from: reconcile.yml
  when:
    - groups.get('gateway_groups', []) | length > 0
    - inventory_hostname == groups['gateway_groups'][0]

- name: Reconcile controller
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.automationcontroller
    tasks_from: reconcile.yml
  when:
    - groups.get('controller_groups', []) | length > 0
    - inventory_hostname == groups['controller_groups'][0]

- name: Reconcile hub
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.automationhub
    tasks_from: reconcile.yml
  when:
    - groups.get('hub_groups', []) | length > 0
    - inventory_hostname == groups['hub_groups'][0]

- name: Reconcile EDA
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.automationeda
    tasks_from: reconcile.yml
  when:
    - groups.get('eda_groups', []) | length > 0
    - inventory_hostname == groups['eda_groups'][0]
