---
- name: Set component config
  ansible.builtin.set_fact:
    _operations_current_component: "{{ _operations_component_config[component_name] }}"

# --- Controller-specific: pre-create database partitions ---
- name: Ensure the database partitions are created (RPM)
  when:
    - _operations_current_component.has_db_partitions | bool
    - aap_platform is defined
    - aap_platform == 'rpm'
  block:
    - name: Precreate database partitions to avoid pg_dump locks
      ansible.builtin.command: '{{ _operations_current_component.manage_cmd }} precreate_partitions --count={{ precreate_partition_hours | default(3) }}'
      become_user: "{{ _operations_current_component.django_user }}"
      become: true
      register: _operations_result
      changed_when: "'Created partitions for' in _operations_result.stdout"
      failed_when: "'Created partitions for' not in _operations_result.stdout"
  rescue:
    - name: Manage command failed
      ansible.builtin.debug:
        msg: "Task ran into an error while attempting to precreate db partitions."

- name: Ensure the database partitions are created (containerized)
  when:
    - _operations_current_component.has_db_partitions | bool
    - aap_platform is defined
    - aap_platform == 'containerized'
  block:
    - name: Precreate database partitions to avoid pg_dump locks
      containers.podman.podman_container_exec:
        name: "{{ _operations_current_component.container_name }}"
        command: '{{ _operations_current_component.manage_cmd }} precreate_partitions --count={{ precreate_partition_hours | default(3) }}'
      register: _operations_result
      changed_when: "'Created partitions for' in _operations_result.stdout"
      failed_when: "'Created partitions for' not in _operations_result.stdout"

# --- Database export for all components ---
- name: "Export postgresql for {{ component_name }}"
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.postgresql
    tasks_from: db_export.yml
  vars:
    postgresql_component_name: "{{ component_name }}"
    postgresql_django_manage_user: "{{ _operations_current_component.django_user }}"
    postgresql_django_manage_cmd: "{{ _operations_current_component.manage_cmd }}"
    postgresql_django_manage_get_cmd: "{{ _operations_current_component.django_manage_get_cmd | default(omit, true) }}"
    postgresql_django_environment: "{{ _operations_current_component.django_environment if _operations_current_component.django_environment | length > 0 else omit }}"
    postgresql_container_name: '{{ _operations_current_component.container_name }}'
    postgresql_no_log: '{{ __operations_no_log }}'
