---
- name: Get DB credentials for {{ _discover_component_name }}
  ansible.builtin.include_tasks: get_db_credentials.yml
  vars:
    component_name: "{{ _discover_component_name }}"

- name: Save {{ _discover_component_name }} DB credentials
  ansible.builtin.set_fact:
    _artifact_db_credentials: >-
      {{ _artifact_db_credentials | combine({
        _discover_component_name: {
          'host': _operations_db_host,
          'port': _operations_db_port,
          'user': _operations_db_user,
          'password': _operations_db_password,
          'admin_password': _operations_db_admin_password
        }
      }) }}
  no_log: true
