---
- name: Set component config
  ansible.builtin.set_fact:
    _operations_current_component: "{{ _operations_component_config[component_name] }}"

- name: "Get OCP DB credentials"
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.ocp_utils
    tasks_from: get_db_credentials.yml
  vars:
    ocp_pg_config_secret: "{{ _operations_current_component.postgres_secret }}"
  when: aap_platform == 'operator'

- name: "Bridge OCP DB credentials"
  ansible.builtin.set_fact:
    _operations_db_host: "{{ _ocp_utils_db_host }}"
    _operations_db_port: "{{ _ocp_utils_db_port }}"
    _operations_db_name: "{{ _ocp_utils_db_name }}"
    _operations_db_user: "{{ _ocp_utils_db_user }}"
    _operations_db_password: "{{ _ocp_utils_db_password }}"
    _operations_db_admin_password: "{{ _ocp_utils_db_admin_password }}"
  no_log: "{{ __operations_no_log }}"
  when: aap_platform == 'operator'

- name: "Get containerized DB credentials"
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.postgresql
    tasks_from: db_auth.yml
  vars:
    postgresql_component_name: "{{ component_name }}"
    postgresql_django_manage_user: "{{ _operations_current_component.django_user }}"
    postgresql_django_manage_cmd: "{{ _operations_current_component.manage_cmd }}"
    postgresql_django_manage_get_cmd: "{{ _operations_current_component.django_manage_get_cmd | default(omit) }}"
    postgresql_django_environment: "{{ _operations_current_component.django_environment | default({}) }}"
    postgresql_container_name: "{{ _operations_current_component.container_name }}"
  when: aap_platform == 'containerized'

- name: Set containerized DB credential facts
  ansible.builtin.set_fact:
    _operations_db_host: "{{ postgresql_auth_settings.default.HOST }}"
    _operations_db_port: "{{ postgresql_auth_settings.default.PORT }}"
    _operations_db_user: "{{ postgresql_auth_settings.default.USER }}"
    _operations_db_password: "{{ postgresql_auth_settings.default.PASSWORD }}"
    _operations_db_admin_password: "{{ postgresql_admin_password }}"
  no_log: "{{ __operations_no_log }}"
  when: aap_platform == 'containerized'
