---
- name: Read component admin password secret
  kubernetes.core.k8s_info:
    kind: Secret
    namespace: "{{ ocp_utils_ocp_namespace }}"
    name: "{{ operations_aap_instance_name }}-{{ _operations_current_component.admin_password_secret }}"
  register: _operations_component_admin_secret
  no_log: "{{ not (disable_no_log | default(false) | bool) }}"

- name: Reset admin password to match K8s secret
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.ocp_utils
    tasks_from: run_manage_command.yml
  vars:
    _manage_label: "{{ _current_component_name }} reset admin password"
    _manage_command: >-
      {{ _operations_current_component.manage_cmd }}
      {{ _operations_current_component.admin_password_cmd }}
      '{{ _operations_component_admin_secret.resources[0].data.password | b64decode }}'
    _manage_pod_name: "{{ _reset_pod_name }}"
    _manage_container_name: "{{ _reset_container_name }}"
  no_log: "{{ not (disable_no_log | default(false) | bool) }}"
  when: _operations_component_admin_secret.resources | length > 0
