---
- name: Set component config
  ansible.builtin.set_fact:
    _operations_current_component: "{{ _operations_component_config[component_name] }}"

- name: "Update OCP secret"
  kubernetes.core.k8s:
    kind: Secret
    name: "{{ _operations_current_component.k8s_secret_name }}"
    namespace: "{{ operations_ocp_namespace }}"
    state: patched
    definition:
      data: "{{ {_operations_current_component.k8s_secret_field: artifact_secrets[_operations_current_component.secret_keys[0]]} }}"
  no_log: "{{ __operations_no_log }}"
  when:
    - aap_platform == 'operator'
    - artifact_secrets[_operations_current_component.secret_keys[0]] is defined

- name: "Update OCP extra secrets"
  kubernetes.core.k8s:
    kind: Secret
    name: "{{ item.secret_name }}"
    namespace: "{{ operations_ocp_namespace }}"
    state: patched
    definition:
      data: "{{ {item.field: artifact_secrets[item.artifact_key]} }}"
  loop: "{{ _operations_current_component.ocp_extra_secrets | default([]) }}"
  loop_control:
    label: "{{ item.secret_name }}"
  no_log: "{{ __operations_no_log }}"
  when:
    - aap_platform == 'operator'
    - _operations_current_component.ocp_extra_secrets is defined
    - artifact_secrets[item.artifact_key] is defined

- name: "Update containerized podman secrets (multi)"
  containers.podman.podman_secret:
    name: "{{ item.name }}"
    data: "{{ artifact_secrets[item.artifact_key] | b64decode }}"
    state: present
    force: true
  no_log: "{{ __operations_no_log }}"
  loop: "{{ _operations_current_component.podman_secrets }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - aap_platform == 'containerized'
    - _operations_current_component.podman_secrets is defined
    - artifact_secrets[item.artifact_key] is defined

- name: "Update containerized podman secret (single)"
  containers.podman.podman_secret:
    name: "{{ _operations_current_component.podman_secret_name }}"
    data: "{{ artifact_secrets[_operations_current_component.secret_keys[0]] | b64decode }}"
    state: present
    force: true
  no_log: "{{ __operations_no_log }}"
  when:
    - aap_platform == 'containerized'
    - _operations_current_component.podman_secret_name is defined
    - _operations_current_component.podman_secrets is not defined
    - artifact_secrets[_operations_current_component.secret_keys[0]] is defined
