---
- name: Preflight checks
  hosts: localhost
  gather_facts: false
  connection: local
  become: false
  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Run variable preflight checks
      ansible.builtin.import_role:
        name: preflight

- name: Stop Monitoring Services
  hosts: automationcontroller:automationhub:automationeda:automationgateway
  gather_facts: false
  tasks:
    - name: Stop monitoring service
      ansible.builtin.import_role:
        name: pcp
        tasks_from: stop_service.yml

- name: Stop EDA Services
  hosts: automationeda
  gather_facts: false
  tasks:
    - name: Stop all EDA services
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationeda
        tasks_from: stop_service.yml

- name: Stop Hub Services
  hosts: automationhub
  gather_facts: false
  tasks:
    - name: Stop all Hub services
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationhub
        tasks_from: stop_service.yml

- name: Stop Controller Services
  hosts: automationcontroller
  gather_facts: false
  tasks:
    - name: Stop Automation Controller services
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationcontroller
        tasks_from: stop_service.yml

- name: Stop Execution Nodes Services
  hosts: execution_nodes
  gather_facts: false
  tasks:
    - name: Stop Execution Nodes services
      ansible.builtin.import_role:
        name: receptor
        tasks_from: stop_service.yml

- name: Stop Gateway Services
  hosts: automationgateway
  gather_facts: false
  tasks:
    - name: Stop Gateway services
      ansible.builtin.include_role:
        name: ansible.aap_snapshot.automationgateway
        tasks_from: stop_service.yml
