---
name: Collection Certification

on:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  certification:
    uses: ansible-collections/partner-certification-checker/.github/workflows/certification-reusable.yml@6a7d1fe5159620648295b44222c48789008a9660 # v3.0.0
