---
name: Collection Certification

on:
  pull_request:
  workflow_dispatch:

jobs:
  certification:
    uses: ansible-collections/partner-certification-checker/.github/workflows/certification-reusable.yml@v3.0.0
